spring.application.name=location-updator

server.port=8082
server.servlet.context-path=/location-updator

# ===============================
# MYSQL CONNECTION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/dev_location_db
spring.datasource.username=root
spring.datasource.password=Test@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.info.env.enabled=true
management.metrics.enable.all=true
management.health.diskspace.enabled=true

