spring.application.name=search-product-redis
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=root
spring.datasource.password=Test@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.data.redis.host=united-marmoset-124667.upstash.io
spring.data.redis.port=6379
spring.data.redis.password=gQAAAAAAAeb7AAIgcDEzYjY3NTU3ZWNiYWY0MjkxYmQ3NzRhNjBhMDRiNzE5NA
spring.data.redis.ssl.enabled=true

spring.cache.type=redis

# OPTIONAL LOGS
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=DEBUG